spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  h2:
    console:
      enabled: true
    path: "/h2"

  datasource:
    username: sa
    password: sa

  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    defer-datasource-initialization: true
    hibernate:
      hbm2ddl:
        auto=create: create
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        sql: info
